-- ==============================================================================
-- Lumina Window Treatments - 12 Starter Products Seed Data
-- ==============================================================================

-- Clear existing products to ensure clean seed
DELETE FROM products WHERE slug IN (
    'roller-shades',
    'roman-shades',
    'wood-blinds',
    'faux-wood-blinds',
    'cellular-honeycomb-shades',
    'zebra-transitional-shades',
    'vertical-blinds',
    'panel-track-blinds',
    'hunter-douglas-silhouette',
    'hunter-douglas-powerview-motorized',
    'plantation-shutters',
    'outdoor-shades'
);

INSERT INTO products (
    name, slug, category, subcategory, description, short_description, price_min, price_max, 
    images, colors, features, room_types, is_featured, is_bestseller, is_active, brand, lead_time, warranty
) VALUES
(
    'Roller Shades',
    'roller-shades',
    'shades',
    'Modern Roller',
    'Sleek, minimalist custom roller shades featuring smooth cordless glide or motorized control. Available in hundreds of light-filtering, decorative textured, and 100% blackout fabrics tailored to your exact window dimensions.',
    'Clean minimalist lines with effortless light and glare control.',
    89.00,
    240.00,
    '["/images/cat-roller.jpg", "/images/hero-living-room.jpg"]'::jsonb,
    '["White", "Ivory", "Warm Gray", "Charcoal", "Sand", "Midnight Black"]'::jsonb,
    '["Cordless", "Motorized", "Blackout", "Child Safe", "Energy Saving"]'::jsonb,
    '["Living Room", "Bedroom", "Home Office", "Kitchen"]'::jsonb,
    TRUE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '10-12 business days',
    'Limited Lifetime Warranty'
),
(
    'Roman Shades',
    'roman-shades',
    'shades',
    'Tailored Drapery',
    'Handcrafted fabric Roman shades combining the softness of drapery with the functionality of a shade. Features flat fold, waterfall, or pleated styles in premium linen, velvet, and cotton blends.',
    'Elegant cascading fabric folds tailored in linen and textured weaves.',
    120.00,
    380.00,
    '["/images/cat-roman.jpg", "/images/product-main.jpg"]'::jsonb,
    '["Oatmeal Linen", "Soft Cream", "Sage Green", "Charcoal Slate", "Navy Wool"]'::jsonb,
    '["Cordless", "Room Darkening", "Thermal Lining", "Child Safe"]'::jsonb,
    '["Living Room", "Bedroom", "Dining Room", "Home Office"]'::jsonb,
    FALSE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '12-14 business days',
    'Limited Lifetime Warranty'
),
(
    'Wood Blinds',
    'wood-blinds',
    'blinds',
    'Natural Hardwood',
    'Precision-crafted from 100% sustainably harvested North American hardwoods. 2-inch and 2.5-inch slats provide superior directional light regulation with authentic organic wood grain textures.',
    'Authentic 100% North American hardwood for rich warmth and texture.',
    95.00,
    290.00,
    '["/images/cat-wood.jpg"]'::jsonb,
    '["Natural Oak", "Rich Walnut", "Chestnut", "Crisp White", "Espresso"]'::jsonb,
    '["Cordless", "Motorized Tilt", "Child Safe", "UV Resistant"]'::jsonb,
    '["Living Room", "Dining Room", "Home Office", "Den"]'::jsonb,
    FALSE,
    TRUE,
    TRUE,
    'Lumina Custom',
    '10-14 business days',
    'Limited Lifetime Warranty'
),
(
    'Faux Wood Blinds',
    'faux-wood-blinds',
    'blinds',
    'Moisture Resistant',
    'Durable composite polymer blinds engineered to resist moisture, humidity, warping, and cracking. Perfect for high-humidity areas like bathrooms, kitchens, and basements.',
    'High-durability moisture-resistant slats with real wood aesthetic.',
    75.00,
    220.00,
    '["/images/cat-wood.jpg"]'::jsonb,
    '["Bright White", "Off-White", "Alabaster", "Slate Gray"]'::jsonb,
    '["Cordless", "Moisture Resistant", "Child Safe", "Easy Clean"]'::jsonb,
    '["Bathroom", "Kitchen", "Laundry Room", "Basement"]'::jsonb,
    TRUE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '7-10 business days',
    'Limited Lifetime Warranty'
),
(
    'Cellular/Honeycomb Shades',
    'cellular-honeycomb-shades',
    'shades',
    'Energy Saving',
    'Engineered with insulating honeycomb air pockets that trap hot and cold air at the windowpane, reducing heating and cooling utility costs by up to 25% while gently diffusing daylight.',
    'Superior thermal insulation trapping air to slash energy bills year-round.',
    110.00,
    310.00,
    '["/images/cat-cellular.jpg"]'::jsonb,
    '["Pure White", "Linen Sand", "Soft Cloud", "Dark Ash", "Midnight"]'::jsonb,
    '["Energy Saving", "Blackout", "Cordless", "Top-Down Bottom-Up", "Child Safe"]'::jsonb,
    '["Bedroom", "Living Room", "Childrens Room", "Home Office"]'::jsonb,
    FALSE,
    TRUE,
    TRUE,
    'Lumina Custom',
    '10-12 business days',
    'Limited Lifetime Warranty'
),
(
    'Zebra/Transitional Shades',
    'zebra-transitional-shades',
    'shades',
    'Dual Layer',
    'Innovative alternating bands of sheer and solid light-filtering fabric that glide past each other to seamlessly transition between an open view, soft filtered light, and full privacy.',
    'Alternating sheer and privacy vanes for modern customizable light control.',
    99.00,
    280.00,
    '["/images/hero-living-room.jpg"]'::jsonb,
    '["Chalk White", "Smoke Gray", "Taupe", "Graphite"]'::jsonb,
    '["Cordless", "Motorized", "Child Safe", "Modern Profile"]'::jsonb,
    '["Living Room", "Dining Room", "Master Suite", "Home Office"]'::jsonb,
    FALSE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '10-14 business days',
    'Limited Lifetime Warranty'
),
(
    'Vertical Blinds',
    'vertical-blinds',
    'blinds',
    'Sliding Doors & Large Windows',
    'Versatile smooth-gliding vertical vanes built specifically for wide patio sliding glass doors, French doors, and oversized panoramic window walls.',
    'Smooth-gliding vertical vanes engineered for wide sliding glass doors.',
    85.00,
    250.00,
    '["/images/service-install.jpg"]'::jsonb,
    '["Arctic White", "Oyster", "Textured Cream", "Charcoal"]'::jsonb,
    '["Wand Control", "Motorized Traverse", "Easy Clean", "Large Openings"]'::jsonb,
    '["Living Room", "Patio / Sunroom", "Dining Room"]'::jsonb,
    FALSE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '10-12 business days',
    'Limited Lifetime Warranty'
),
(
    'Panel Track Blinds',
    'panel-track-blinds',
    'blinds',
    'Modern Sliding Panels',
    'A contemporary alternative to traditional vertical blinds featuring wide fabric panels that slide effortlessly on a multi-channel aluminum track system. Also ideal as room dividers.',
    'Sleek sliding architectural fabric panels for French doors & large vistas.',
    120.00,
    350.00,
    '["/images/cat-roller.jpg"]'::jsonb,
    '["Woven Jute", "Natural Flax", "Stone Gray", "Off White"]'::jsonb,
    '["Cordless Wand", "Room Divider", "Solar Glare Control", "Child Safe"]'::jsonb,
    '["Living Room", "Open Concept Space", "Commercial Conference Room"]'::jsonb,
    FALSE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '12-15 business days',
    'Limited Lifetime Warranty'
),
(
    'Hunter Douglas Silhouette',
    'hunter-douglas-silhouette',
    'shades',
    'Luxury Sheer Vanes',
    'Signature luxury window shadings with S-shaped fabric vanes suspended between two sheer fabric facings. Transforms harsh sunlight into soft ambient illumination while preserving exterior views.',
    'Signature luxury S-vanes suspended between two sheer ambient panels.',
    280.00,
    680.00,
    '["/images/product-main.jpg", "/images/hero-living-room.jpg"]'::jsonb,
    '["White Diamond", "Misty Morning", "Sunlit Linen", "Titanium Gray"]'::jsonb,
    '["Luxury Vanes", "UV Filtering 99%", "PowerView Motorized", "Child Safe"]'::jsonb,
    '["Living Room", "Master Bedroom", "Formal Dining", "Executive Office"]'::jsonb,
    TRUE,
    TRUE,
    TRUE,
    'Hunter Douglas',
    '14-18 business days',
    'Hunter Douglas Lifetime Guarantee'
),
(
    'Hunter Douglas PowerView Motorized',
    'hunter-douglas-powerview-motorized',
    'motorized',
    'Smart Home Automation',
    'World-class whisper-quiet smart motorized shades compatible with Apple HomeKit, Amazon Alexa, Google Home, and Matter. Set automated schedules based on local Gaithersburg sunrise & sunset.',
    'Award-winning whisper-quiet smart shades with voice and mobile automation.',
    350.00,
    900.00,
    '["/images/hero-business.jpg", "/images/business-meeting.jpg"]'::jsonb,
    '["Frost", "Pebble Gray", "Graphite", "Warm Sand", "Onyx"]'::jsonb,
    '["Motorized", "Matter / Alexa / HomeKit", "Rechargeable Lithium", "Schedules"]'::jsonb,
    '["Living Room", "Bedroom", "Home Theater", "High Windows"]'::jsonb,
    TRUE,
    FALSE,
    TRUE,
    'Hunter Douglas',
    '14-20 business days',
    'Hunter Douglas 5-Year Motor Warranty'
),
(
    'Plantation Shutters',
    'plantation-shutters',
    'shutters',
    'Custom Wood & Poly',
    'Architectural custom interior plantation shutters with 3.5-inch or 4.5-inch louvers. Built to exact frame specs with hidden tilt rods and mortise-and-tenon craftsmanship.',
    'Permanent architectural luxury adding lasting equity to your home.',
    250.00,
    650.00,
    '["/images/cat-wood.jpg", "/images/product-main.jpg"]'::jsonb,
    '["Bright White", "Silk White", "Warm Cream", "Chestnut Stain"]'::jsonb,
    '["Hidden Tilt", "Insulating", "Child Safe", "Permanent Equity"]'::jsonb,
    '["Living Room", "Master Suite", "Dining Room", "Entryway"]'::jsonb,
    FALSE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '18-24 business days',
    'Lifetime Craftsmanship Warranty'
),
(
    'Outdoor Shades',
    'outdoor-shades',
    'outdoor',
    'Weatherproof Exterior',
    'Heavy-duty exterior motorized and crank-operated solar shades engineered for patios, decks, pergolas, and outdoor porches across the DMV. Resists wind, rain, mold, and blocks up to 95% of solar heat.',
    'Weatherproof exterior solar drop shades for patios, decks, and pergolas.',
    150.00,
    450.00,
    '["/images/hero-business.jpg"]'::jsonb,
    '["Charcoal Bronze", "Desert Sand", "Slate Gray", "Polar White"]'::jsonb,
    '["Weatherproof", "Wind Retention Tracks", "Motorized", "UV Heat Rejection"]'::jsonb,
    '["Patio", "Deck", "Pergola", "Screened Porch", "Commercial Terrace"]'::jsonb,
    FALSE,
    FALSE,
    TRUE,
    'Lumina Custom',
    '14-18 business days',
    '10-Year Exterior Fabric Warranty'
);

-- Seed DMV Sample Installers
DELETE FROM installers WHERE email IN ('marcus.t@luminablinds.com', 'dave.k@luminablinds.com');

INSERT INTO installers (name, email, phone, active) VALUES
('Marcus Taylor (Lead DMV Installer)', 'marcus.t@luminablinds.com', '(240) 555-0142', TRUE),
('Dave Kowalski (Master Technician - Northern VA)', 'dave.k@luminablinds.com', '(703) 555-0188', TRUE);
