export const STARTER_PRODUCTS = [
  {
    name: 'Roller Shades',
    slug: 'roller-shades',
    category: 'shades',
    subcategory: 'Modern Roller',
    description: 'Sleek, minimalist custom roller shades featuring smooth cordless glide or motorized control. Available in hundreds of light-filtering, decorative textured, and 100% blackout fabrics tailored to your exact window dimensions.',
    short_description: 'Clean minimalist lines with effortless light and glare control.',
    price_min: 89.00,
    price_max: 240.00,
    images: ['/images/cat-roller.jpg', '/images/hero-living-room.jpg'],
    colors: ['White', 'Ivory', 'Warm Gray', 'Charcoal', 'Sand', 'Midnight Black'],
    features: ['Cordless', 'Motorized', 'Blackout', 'Child Safe', 'Energy Saving'],
    room_types: ['Living Room', 'Bedroom', 'Home Office', 'Kitchen'],
    is_featured: true,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-12 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Roman Shades',
    slug: 'roman-shades',
    category: 'shades',
    subcategory: 'Tailored Drapery',
    description: 'Handcrafted fabric Roman shades combining the softness of drapery with the functionality of a shade. Features flat fold, waterfall, or pleated styles in premium linen, velvet, and cotton blends.',
    short_description: 'Elegant cascading fabric folds tailored in linen and textured weaves.',
    price_min: 120.00,
    price_max: 380.00,
    images: ['/images/cat-roman.jpg', '/images/product-main.jpg'],
    colors: ['Oatmeal Linen', 'Soft Cream', 'Sage Green', 'Charcoal Slate', 'Navy Wool'],
    features: ['Cordless', 'Room Darkening', 'Thermal Lining', 'Child Safe'],
    room_types: ['Living Room', 'Bedroom', 'Dining Room', 'Home Office'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '12-14 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Woven Wood & Bamboo Shades',
    slug: 'woven-wood-shades',
    category: 'shades',
    subcategory: 'Natural Organic Woven',
    description: 'Handcrafted from 100% natural, renewable bamboo, reeds, wild grasses, and jute. Adds rich organic texture and warm earthy tones to any space. Available with independent privacy or blackout liners and edge-binding accents.',
    short_description: 'Artisanal organic bamboo, jute, and grasses bringing earthy warmth indoors.',
    price_min: 115.00,
    price_max: 340.00,
    images: ['/images/cat-roman.jpg', '/images/cat-roller.jpg'],
    colors: ['Natural Bamboo', 'Driftwood Jute', 'Toasted Wheat', 'Honey Cane', 'Espresso Reed'],
    features: ['Cordless', 'Motorized', 'Natural Organic', 'Optional Blackout Liner', 'Edge Binding'],
    room_types: ['Living Room', 'Sunroom', 'Dining Room', 'Primary Bedroom'],
    is_featured: true,
    is_bestseller: true,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '12-15 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Solar Screen Shades',
    slug: 'solar-shades',
    category: 'shades',
    subcategory: 'Sun & Glare Protection',
    description: 'High-performance engineered solar screen fabric shades designed to block up to 99% of damaging UV rays and harsh glare while maintaining crisp daytime views of the outdoors. Available in 1%, 3%, 5%, and 10% openness weaves.',
    short_description: 'Advanced UV heat & glare rejection while preserving your scenic outdoor view.',
    price_min: 95.00,
    price_max: 260.00,
    images: ['/images/cat-roller.jpg', '/images/hero-business.jpg'],
    colors: ['Solar Chalk 3%', 'Solar Ash 5%', 'Solar Bronze 1%', 'Solar Charcoal 3%'],
    features: ['UV Heat Rejection', 'Glare Reduction', 'Cordless', 'Motorized', 'Energy Saving'],
    room_types: ['Home Office', 'Living Room', 'Kitchen', 'Commercial Glass Vistas'],
    is_featured: true,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-12 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Top-Down / Bottom-Up Cellular Shades',
    slug: 'top-down-bottom-up-shades',
    category: 'shades',
    subcategory: 'Versatile Privacy & Light',
    description: 'The ultimate in lighting versatility. Lower the shade from the top to invite glorious natural daylight and blue sky while keeping the lower half closed for complete privacy from street views. Features insulating honeycomb cells.',
    short_description: 'Lower from top for daylight while maintaining complete bottom privacy.',
    price_min: 125.00,
    price_max: 340.00,
    images: ['/images/cat-cellular.jpg'],
    colors: ['Crisp White', 'Linen Sand', 'Misty Gray', 'Soft Cloud', 'Midnight Navy'],
    features: ['Top-Down Bottom-Up', 'Thermal Honeycomb Insulation', 'Cordless', 'Child Safe'],
    room_types: ['Street-Level Townhome', 'Bathroom', 'Bedroom', 'Home Office'],
    is_featured: true,
    is_bestseller: true,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-14 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Wood Blinds',
    slug: 'wood-blinds',
    category: 'blinds',
    subcategory: 'Natural Hardwood',
    description: 'Precision-crafted from 100% sustainably harvested North American hardwoods. 2-inch and 2.5-inch slats provide superior directional light regulation with authentic organic wood grain textures.',
    short_description: 'Authentic 100% North American hardwood for rich warmth and texture.',
    price_min: 95.00,
    price_max: 290.00,
    images: ['/images/cat-wood.jpg'],
    colors: ['Natural Oak', 'Rich Walnut', 'Chestnut', 'Crisp White', 'Espresso'],
    features: ['Cordless', 'Motorized Tilt', 'Child Safe', 'UV Resistant'],
    room_types: ['Living Room', 'Dining Room', 'Home Office', 'Den'],
    is_featured: false,
    is_bestseller: true,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-14 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Faux Wood Blinds',
    slug: 'faux-wood-blinds',
    category: 'blinds',
    subcategory: 'Moisture Resistant',
    description: 'Durable composite polymer blinds engineered to resist moisture, humidity, warping, and cracking. Perfect for high-humidity areas like bathrooms, kitchens, and basements.',
    short_description: 'High-durability moisture-resistant slats with real wood aesthetic.',
    price_min: 75.00,
    price_max: 220.00,
    images: ['/images/cat-wood.jpg'],
    colors: ['Bright White', 'Off-White', 'Alabaster', 'Slate Gray'],
    features: ['Cordless', 'Moisture Resistant', 'Child Safe', 'Easy Clean'],
    room_types: ['Bathroom', 'Kitchen', 'Laundry Room', 'Basement'],
    is_featured: true,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '7-10 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Aluminum Mini Blinds',
    slug: 'aluminum-mini-blinds',
    category: 'blinds',
    subcategory: 'Durable 1" Aluminum',
    description: 'Constructed from heavy 6-gauge spring-tempered recycled aluminum slats that bounce back against bending and rough wear. Modern dust-resistant finish makes them a reliable, budget-conscious choice for residential rentals, commercial offices, and utility rooms.',
    short_description: 'Heavy-gauge spring-tempered aluminum blinds built for high durability & easy cleaning.',
    price_min: 55.00,
    price_max: 160.00,
    images: ['/images/service-install.jpg', '/images/cat-wood.jpg'],
    colors: ['Brushed Aluminum', 'Gloss White', 'Matte Black', 'Silver Metallic', 'Alabaster'],
    features: ['Cordless Wand', 'Heavy 6-Gauge Aluminum', 'Dust Resistant', 'Commercial Grade'],
    room_types: ['Home Office', 'Rental Property', 'Basement', 'Commercial Facility'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '7-10 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Cellular/Honeycomb Shades',
    slug: 'cellular-honeycomb-shades',
    category: 'shades',
    subcategory: 'Energy Saving',
    description: 'Engineered with insulating honeycomb air pockets that trap hot and cold air at the windowpane, reducing heating and cooling utility costs by up to 25% while gently diffusing daylight.',
    short_description: 'Superior thermal insulation trapping air to slash energy bills year-round.',
    price_min: 110.00,
    price_max: 310.00,
    images: ['/images/cat-cellular.jpg'],
    colors: ['Pure White', 'Linen Sand', 'Soft Cloud', 'Dark Ash', 'Midnight'],
    features: ['Energy Saving', 'Blackout', 'Cordless', 'Top-Down Bottom-Up', 'Child Safe'],
    room_types: ['Bedroom', 'Living Room', 'Childrens Room', 'Home Office'],
    is_featured: false,
    is_bestseller: true,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-12 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Zebra/Transitional Shades',
    slug: 'zebra-transitional-shades',
    category: 'shades',
    subcategory: 'Dual Layer',
    description: 'Innovative alternating bands of sheer and solid light-filtering fabric that glide past each other to seamlessly transition between an open view, soft filtered light, and full privacy.',
    short_description: 'Alternating sheer and privacy vanes for modern customizable light control.',
    price_min: 99.00,
    price_max: 280.00,
    images: ['/images/hero-living-room.jpg'],
    colors: ['Chalk White', 'Smoke Gray', 'Taupe', 'Graphite'],
    features: ['Cordless', 'Motorized', 'Child Safe', 'Modern Profile'],
    room_types: ['Living Room', 'Dining Room', 'Master Suite', 'Home Office'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-14 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Custom Tailored Drapery',
    slug: 'custom-drapery',
    category: 'drapery',
    subcategory: 'Handcrafted Drapery & Curtains',
    description: 'Custom full-length drapery panels tailored by master artisans in French Pinch Pleat, Tailored Ripplefold, and Modern Grommet styles. Choose from heavy Belgian linens, plush velvets, and sheer silks with blackout or thermal acoustic linings.',
    short_description: 'Luxury floor-to-ceiling drapery in Belgian linen, velvet, and acoustic thermal liners.',
    price_min: 180.00,
    price_max: 650.00,
    images: ['/images/product-main.jpg', '/images/cat-roman.jpg'],
    colors: ['Belgian Natural Linen', 'Champagne Silk', 'Midnight Velvet', 'Charcoal Wool', 'Ivory Sheer'],
    features: ['Pinch Pleat', 'Ripplefold', 'Blackout Thermal Lining', 'Acoustic Sound Dampening', 'Motorized Traverse Track'],
    room_types: ['Formal Living Room', 'Master Bedroom', 'Formal Dining', 'Grand Entryway'],
    is_featured: true,
    is_bestseller: true,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '14-18 business days',
    warranty: 'Lifetime Craftsmanship Guarantee'
  },
  {
    name: 'Vertical Blinds',
    slug: 'vertical-blinds',
    category: 'blinds',
    subcategory: 'Sliding Doors & Large Windows',
    description: 'Versatile smooth-gliding vertical vanes built specifically for wide patio sliding glass doors, French doors, and oversized panoramic window walls.',
    short_description: 'Smooth-gliding vertical vanes engineered for wide sliding glass doors.',
    price_min: 85.00,
    price_max: 250.00,
    images: ['/images/service-install.jpg'],
    colors: ['Arctic White', 'Oyster', 'Textured Cream', 'Charcoal'],
    features: ['Wand Control', 'Motorized Traverse', 'Easy Clean', 'Large Openings'],
    room_types: ['Living Room', 'Patio / Sunroom', 'Dining Room'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '10-12 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Panel Track Blinds',
    slug: 'panel-track-blinds',
    category: 'blinds',
    subcategory: 'Modern Sliding Panels',
    description: 'A contemporary alternative to traditional vertical blinds featuring wide fabric panels that slide effortlessly on a multi-channel aluminum track system. Also ideal as room dividers.',
    short_description: 'Sleek sliding architectural fabric panels for French doors & large vistas.',
    price_min: 120.00,
    price_max: 350.00,
    images: ['/images/cat-roller.jpg'],
    colors: ['Woven Jute', 'Natural Flax', 'Stone Gray', 'Off White'],
    features: ['Cordless Wand', 'Room Divider', 'Solar Glare Control', 'Child Safe'],
    room_types: ['Living Room', 'Open Concept Space', 'Commercial Conference Room'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '12-15 business days',
    warranty: 'Limited Lifetime Warranty'
  },
  {
    name: 'Hunter Douglas Silhouette',
    slug: 'hunter-douglas-silhouette',
    category: 'shades',
    subcategory: 'Luxury Sheer Vanes',
    description: 'Signature luxury window shadings with S-shaped fabric vanes suspended between two sheer fabric facings. Transforms harsh sunlight into soft ambient illumination while preserving exterior views.',
    short_description: 'Signature luxury S-vanes suspended between two sheer ambient panels.',
    price_min: 280.00,
    price_max: 680.00,
    images: ['/images/product-main.jpg', '/images/hero-living-room.jpg'],
    colors: ['White Diamond', 'Misty Morning', 'Sunlit Linen', 'Titanium Gray'],
    features: ['Luxury Vanes', 'UV Filtering 99%', 'PowerView Motorized', 'Child Safe'],
    room_types: ['Living Room', 'Master Bedroom', 'Formal Dining', 'Executive Office'],
    is_featured: true,
    is_bestseller: true,
    is_active: true,
    brand: 'Hunter Douglas',
    lead_time: '14-18 business days',
    warranty: 'Hunter Douglas Lifetime Guarantee'
  },
  {
    name: 'Hunter Douglas PowerView Motorized',
    slug: 'hunter-douglas-powerview-motorized',
    category: 'motorized',
    subcategory: 'Smart Home Automation',
    description: 'World-class whisper-quiet smart motorized shades compatible with Apple HomeKit, Amazon Alexa, Google Home, and Matter. Set automated schedules based on local Gaithersburg sunrise & sunset.',
    short_description: 'Award-winning whisper-quiet smart shades with voice and mobile automation.',
    price_min: 350.00,
    price_max: 900.00,
    images: ['/images/hero-business.jpg', '/images/business-meeting.jpg'],
    colors: ['Frost', 'Pebble Gray', 'Graphite', 'Warm Sand', 'Onyx'],
    features: ['Motorized', 'Matter / Alexa / HomeKit', 'Rechargeable Lithium', 'Schedules'],
    room_types: ['Living Room', 'Bedroom', 'Home Theater', 'High Windows'],
    is_featured: true,
    is_bestseller: false,
    is_active: true,
    brand: 'Hunter Douglas',
    lead_time: '14-20 business days',
    warranty: 'Hunter Douglas 5-Year Motor Warranty'
  },
  {
    name: 'Plantation Shutters',
    slug: 'plantation-shutters',
    category: 'shutters',
    subcategory: 'Custom Wood & Poly',
    description: 'Architectural custom interior plantation shutters with 3.5-inch or 4.5-inch louvers. Built to exact frame specs with hidden tilt rods and mortise-and-tenon craftsmanship.',
    short_description: 'Permanent architectural luxury adding lasting equity to your home.',
    price_min: 250.00,
    price_max: 650.00,
    images: ['/images/cat-wood.jpg', '/images/product-main.jpg'],
    colors: ['Bright White', 'Silk White', 'Warm Cream', 'Chestnut Stain'],
    features: ['Hidden Tilt', 'Insulating', 'Child Safe', 'Permanent Equity'],
    room_types: ['Living Room', 'Master Suite', 'Dining Room', 'Entryway'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '18-24 business days',
    warranty: 'Lifetime Craftsmanship Warranty'
  },
  {
    name: 'Outdoor Shades',
    slug: 'outdoor-shades',
    category: 'outdoor',
    subcategory: 'Weatherproof Exterior',
    description: 'Heavy-duty exterior motorized and crank-operated solar shades engineered for patios, decks, pergolas, and outdoor porches across the DMV. Resists wind, rain, mold, and blocks up to 95% of solar heat.',
    short_description: 'Weatherproof exterior solar drop shades for patios, decks, and pergolas.',
    price_min: 150.00,
    price_max: 450.00,
    images: ['/images/hero-business.jpg'],
    colors: ['Charcoal Bronze', 'Desert Sand', 'Slate Gray', 'Polar White'],
    features: ['Weatherproof', 'Wind Retention Tracks', 'Motorized', 'UV Heat Rejection'],
    room_types: ['Patio', 'Deck', 'Pergola', 'Screened Porch', 'Commercial Terrace'],
    is_featured: false,
    is_bestseller: false,
    is_active: true,
    brand: 'Lumina Custom',
    lead_time: '14-18 business days',
    warranty: '10-Year Exterior Fabric Warranty'
  }
];
